language: android
android:
  components:
    - tools
    - platform-tools-30.0.4
    - build-tools-30.0.4
    - android-30
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

notifications:
  email:
    - eranbou@gmail.com

script:
- ./gradlew clean assembleDebug test lint

before_install:
  - yes | sdkmanager --update
