package com.mitteloupe.randomgen.fielddataprovider

import com.mitteloupe.randomgen.FieldDataProvider

private const val DEFAULT_DELIMITER = ""

/**
 * Created by Eran Boudjnah on 15/08/2018.
 */
class ConcatenateFieldDataProvider<OUTPUT_TYPE>
/**
 * Returns a new instance of [ConcatenateFieldDataProvider] generating a concatenated [String] of
 * the outputs generated by the provided [FieldDataProvider] instances using the provided delimiter.
 *
 * @param delimiter          The delimiter to use when concatenating. Defaults to [DEFAULT_DELIMITER]
 * @param fieldDataProviders Concatenate the output of these FieldDataProvider instances
 */
@SafeVarargs
constructor(
	vararg fieldDataProviders: FieldDataProvider<OUTPUT_TYPE, *>,
	private val delimiter: String = DEFAULT_DELIMITER
) : FieldDataProvider<OUTPUT_TYPE, String> {

	private val fieldDataProviders: List<FieldDataProvider<OUTPUT_TYPE, *>> = fieldDataProviders.toList()

	override fun generate(instance: OUTPUT_TYPE?): String {
		val result = StringBuilder()

		for (fieldDataProvider in fieldDataProviders) {
			result
				.append(fieldDataProvider.generate(instance))
				.append(delimiter)
		}

		if (result.isNotEmpty() && delimiter.isNotEmpty()) {
			result.delete(result.length - delimiter.length, result.length)
		}

		return result.toString()
	}
}
